server:
  port: 9001

# tag::configuration-eureka[]
eureka:  #<1>
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    statusPageUrlPath: /actuator/info      #状态地址
    healthCheckUrlPath: /actuator/health   #健康检查地址
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*" #<2>
  endpoint:
    health:
      show-details: ALWAYS
# end::configuration-eureka[]
      
spring:
  cloud:
    config:
      name: bootstrap,application,demo
      label: dev
      profile: ${spring.application.name}
      uri: ${CONFIG_SERVICE_URL:http://localhost:8787}

logging:
  file: "target/${spring.application.name}.log"