server:
  port: 9001

eureka:   #<1>
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    statusPageUrlPath: /actuator/info      #状态地址
    healthCheckUrlPath: /actuator/health   #健康检查地址
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

spring:
  cloud:
    config:
      name: application,bootstrap
      profile: ${spring.application.name}
      url: ${CONFIG_SERVICE_URL:http://localhost:8888}      